heem_concept_type_labels = ['Emotie', 'Lichaamswerking', 'Lichaamsdeel',
                            'EmotioneleHandeling']

heem_emotion_labels = ['Achterdocht', 'Angst', 'Bedruktheid',
                       'Beledigd', 'Berusting', 'Bezorgdheid', 'Blijdschap',
                       'Eergevoel', 'Geluk', 'Gemis', 'Haat', 'Hebzucht',
                       'Hoop', 'Jaloezie', 'Liefde', 'Mededogen', 'Ongeluk',
                       'Ontroering', 'Ontzag', 'Opluchting', 'Overig',
                       'Schaamte', 'Teleurstelling', 'Toewijding', 'Trots',
                       'Trouw', 'Verdriet', 'Verlangen', 'Vertrouwen',
                       'Verwondering', 'Walging', 'Wanhoop', 'Welwillendheid',
                       'Woede', 'Wraakzucht', 'Wrevel', 'Wroeging', 'Wrok']

heem_humor_modifier_labels = ['ontkennend', 'koud', 'donker', 'hard', 'zoet',
                              'droog', 'warm', 'samentrekkend', 'nat', 'zacht',
                              'zuur', 'uitdijend', 'bitter', 'licht']

heem_intensifier_labels = ['versterkend', 'afzwakkend']

heem_body_part_labels = ["Heart", "Longs", "Jaws", "Ears", "Mind", "Head",
                         "Arms", "Hair", "Bones", "Lips", "Horns",
                         "Throat", "Tooth", "Conscience", "Knees", "Limbs",
                         "Breath", "Liver", "Phlegm", "Wound", "Fingers",
                         "Snot", "Forehead", "Tears", "Legs", "Cheeks",
                         "Body", "Eyes", "Senses", "Stomach", "Wrists",
                         "Nails", "Mouth", "Breast", "Hands", "Marrow",
                         "Varia", "Spirit", "Intestines", "Shoulder",
                         "Feet", "Bile", "Voice", "Neck", "Skull", "Brain",
                         "Soul", "Face", "Sweat", "Shins", "Veins",
                         "Tongue", "Womb", "Blood"]
heem_labels_en = {'Emotie': 'Emotion',
                  'Lichaamswerking': 'BodilyProcess',
                  'Lichaamsdeel': 'BodyPart',
                  'EmotioneleHandeling': 'EmotionalAction',
                  'Achterdocht': 'Suspicion',
                  'Angst': 'Fear',
                  'Bedruktheid': 'HeavyHeartedness',
                  'Beledigd': 'Offended',
                  'Berusting': 'Aquiescence',
                  'Bezorgdheid': 'Worry',
                  'Blijdschap': 'Joy',
                  'Eergevoel': 'Honor',
                  'Geluk': 'Happiness',
                  'Gemis': 'Loss',
                  'Haat': 'Hatred',
                  'Hebzucht': 'Greed',
                  'Hoop': 'Hope',
                  'Jaloezie': 'Envy',
                  'Liefde': 'Love',
                  'Mededogen': 'Compassion',
                  'Ongeluk': 'Unhappiness',
                  'Ontroering': 'Moved',
                  'Ontzag': 'Awe',
                  'Opluchting': 'Relief',
                  'Overig': 'Other',
                  'Schaamte': 'Shame',
                  'Teleurstelling': 'Dissapointment',
                  'Toewijding': 'Dedication',
                  'Trots': 'Pride',
                  'Trouw': 'Loyalty',
                  'Verdriet': 'Sadness',
                  'Verlangen': 'Desire',
                  'Vertrouwen': 'Trust',
                  'Verwondering': 'Wonder',
                  'Walging': 'Disgust',
                  'Wanhoop': 'Despair',
                  'Welwillendheid': 'Benevolence',
                  'Woede': 'Anger',
                  'Wraakzucht': 'Vindictiveness',
                  'Wrevel': 'Annoyance',
                  'Wroeging': 'Remorse',
                  'Wrok': 'Spitefulness'}

heem_modifiers_en = {'ontkennend': 'negation',
                     'koud': 'cold',
                     'versterkend': 'intensifying',
                     'afzwakkend': 'weakening',
                     'donker': 'dark',
                     'hard': 'hard',
                     'zoet': 'sweet',
                     'droog': 'dry',
                     'warm': 'warm',
                     'samentrekkend': 'astringent',
                     'nat': 'wet',
                     'zacht': 'soft',
                     'zuur': 'acid',
                     'uitdijend': 'expanding',
                     'bitter': 'bitter',
                     'licht': 'light'}
